# Generated by Django 5.0.6 on 2024-05-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awakening',
            fields=[
                ('awakening_id', models.AutoField(primary_key=True, serialize=False)),
                ('awakening_name', models.CharField(max_length=15)),
                ('awakening_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderSkill',
            fields=[
                ('lskill_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lskill_name', models.CharField(max_length=60)),
                ('lskill_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=60)),
                ('skill_desc', models.TextField(blank=True)),
                ('turns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('monster_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monster_name', models.CharField(max_length=60)),
                ('lskill_id_lskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.leaderskill')),
                ('root_monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.monster')),
                ('skill_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Monster_Attribute',
            fields=[
                ('monster_att_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monster_attribute', models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Wood', 'Wood'), ('Light', 'Light'), ('Dark', 'Dark'), ('None', 'None')], max_length=10)),
                ('attribute_number', models.IntegerField()),
                ('monster_id_monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.monster')),
            ],
            options={
                'managed': True,
                'unique_together': {('monster_id_monster', 'monster_attribute', 'attribute_number')},
            },
        ),
        migrations.CreateModel(
            name='Monster_Type',
            fields=[
                ('monster_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monster_type', models.CharField(choices=[('God', 'God'), ('Dragon', 'Dragon'), ('Devil', 'Devil'), ('Machine', 'Machine'), ('Balanced', 'Balanced'), ('Attacker', 'Attacker'), ('Physical', 'Physical'), ('Evo-Material', 'Evo-Material'), ('Awaken-Material', 'Awaken-Material'), ('Redeemable-Material', 'Redeemable-Material'), ('Enhance-Material', 'Enhance-Material')], max_length=20)),
                ('monster_id_monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.monster')),
            ],
            options={
                'managed': True,
                'unique_together': {('monster_id_monster', 'monster_type')},
            },
        ),
        migrations.CreateModel(
            name='MonsterAwakening',
            fields=[
                ('monster_awakening_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('awakening_id_awakening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.awakening')),
                ('monster_id_monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.monster')),
            ],
            options={
                'managed': True,
                'unique_together': {('monster_id_monster', 'awakening_id_awakening')},
            },
        ),
    ]
