# Generated by Django 5.0.6 on 2024-06-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0002_alter_leaderskill_lskill_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='ActiveSkill',
        ),
        migrations.RenameField(
            model_name='activeskill',
            old_name='skill_desc',
            new_name='askill_desc',
        ),
        migrations.RenameField(
            model_name='activeskill',
            old_name='skill_id',
            new_name='askill_id',
        ),
        migrations.RenameField(
            model_name='activeskill',
            old_name='skill_name',
            new_name='askill_name',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='skill_id_skill',
            new_name='askill_id_askill',
        ),
        migrations.AddField(
            model_name='monster_type',
            name='type_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='monster_attribute',
            name='monster_attribute',
            field=models.CharField(choices=[('FIRE', 'Fire'), ('WATER', 'Water'), ('WOOD', 'Wood'), ('LIGHT', 'Light'), ('DARK', 'Dark'), ('EMPTY', 'Empty')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monster_type',
            name='monster_type',
            field=models.CharField(choices=[('GOD', 'God'), ('DRAGON', 'Dragon'), ('DEVIL', 'Devil'), ('MACHINE', 'Machine'), ('BALANCED', 'Balanced'), ('ATTACKER', 'Attacker'), ('PHYSCIAL', 'Physcial'), ('EVO_MATERIAL', 'Evo Material'), ('AWAKEN_MATERIAL', 'Awaken Material'), ('ENHANCE_MATERIAL', 'Enhance Material'), ('REDEEMABLE_MATERIAL', 'Redeemable Material')], max_length=20),
        ),
    ]
